/**
 * api/src/lib/backupRetention.js
 *
 * THE retention policy for the `cosmos-backups` blob container. Pure, side-effect-free,
 * clock-free. This is the ONLY place the policy is expressed (CLAUDE.md mode 2 — one
 * implementation, not two). Both callers require it:
 *
 *   - scripts/prune_backups.js              (operator CLI, dry run by default)
 *   - api/src/functions/backupPrune.js      (scheduled daily timer)
 *
 * It lives in api/src/lib/ because that directory ships inside the Function App zip and
 * is already the established home for shared pure backup logic (backupCore.js). The CLI
 * reaches it with a relative require (`../api/src/lib/backupRetention`); that costs the
 * CLI nothing, because it already requires `../api/node_modules/@azure/storage-blob`.
 * This module itself has ZERO dependencies, so requiring it can never fail for either
 * caller.
 *
 * SCOPE — read this before changing anything here.
 *   This module reasons about BACKUP ARCHIVE BLOBS ONLY, in one hardcoded container.
 *   It has no Cosmos client, no container name parameter, and no filesystem access. It
 *   cannot reach student data, the Cosmos database, the `function-releases` container,
 *   `$web`, or `refactor-baseline/`. It returns names to a caller; it deletes nothing.
 *
 * POLICY
 *   - Keep every archive whose age is <= RETENTION_DAYS (15). Strictly older archives
 *     are candidates for deletion.
 *   - HARD FLOOR: the newest MIN_KEEP_NEWEST (7) archives are never selected, whatever
 *     the day window says. See WHY THE FLOOR IS NEEDED below.
 *   - `cosmos_backup_latest.json` (and its sidecar) are POINTERS, not archives, and are
 *     never selected at any age.
 *   - `backup_FAILED_*` markers and every other blob are never selected.
 *   - A selected archive takes its own `.sha256` sidecar with it, and a sidecar is never
 *     selected on its own.
 *
 * WHY THE FLOOR IS NEEDED INDEPENDENTLY OF THE DAY WINDOW
 *   The day window assumes backups keep succeeding. If the nightly backup breaks — bad
 *   credentials, a Cosmos outage, a deploy that throws before the upload — no new archive
 *   is written, but the clock keeps moving. Sixteen days after the last good backup every
 *   archive in the container is older than 15 days, and a pure day-window prune would
 *   empty the container completely, on schedule, exactly when the backup is already
 *   broken and recovery matters most. The floor makes "we stopped taking backups" cost
 *   nothing rather than cost everything: the newest 7 archives survive indefinitely until
 *   7 newer ones exist to replace them. It is not a tuning knob — it is the guard that
 *   makes automatic deletion safe to leave unattended.
 *
 * AGE SOURCE — filename timestamp vs blob lastModified
 *   Both are used, and the SAFER of the two wins. Measured against the live container
 *   (33 archives, 2026-09-07): every archive name parses strictly, and the filename
 *   timestamp and `lastModified` agree to within 0.73 s, so today they are
 *   interchangeable. They can diverge, though, and the two failure directions are not
 *   symmetric:
 *     - `lastModified` is blob metadata and is bumped forward by any rewrite, copy, tier
 *       change or metadata set. It can therefore make an OLD archive look YOUNG.
 *     - the filename timestamp is immutable once written, but it is generated by the
 *       backup writer and would be wrong if that writer's clock were wrong.
 *   `effectiveMs = max(filenameMs, lastModifiedMs)` — the archive is treated as the
 *   YOUNGER of the two readings, so any disagreement can only ever KEEP a backup longer,
 *   never delete one sooner. A disagreement beyond SKEW_TOLERANCE_MS is reported in
 *   `skewWarnings` so an operator sees it, but it never widens the deletion set.
 *   An archive whose name does not parse strictly, or which has no usable
 *   `lastModified`, is not a candidate at all — it is ignored, never deleted. Unknown
 *   age means keep (CLAUDE.md mode 1: no invented fallback value).
 */

/** Archives strictly older than this many days are candidates for deletion. */
const RETENTION_DAYS = 15;

/** Absolute floor: the newest N archives are never deleted. See the note above. */
const MIN_KEEP_NEWEST = 7;

/** The one container this policy applies to. Hardcoded on purpose; there is no override. */
const BACKUP_CONTAINER = 'cosmos-backups';

/** Loose shape of an archive blob (excludes `*.json.sha256`, which ends in .sha256). */
const ARCHIVE_RE = /^cosmos_backup_.+\.json$/;

/** Strict shape written by performCosmosBackup(): cosmos_backup_<ISO with : . -> ->.json */
const ARCHIVE_TIMESTAMP_RE =
  /^cosmos_backup_(\d{4})-(\d{2})-(\d{2})T(\d{2})-(\d{2})-(\d{2})-(\d{3})Z\.json$/;

/** Mutable pointer to the newest archive. Never an archive in its own right. */
const LATEST_POINTER = 'cosmos_backup_latest.json';

/** Disagreement above this between filename time and lastModified is reported. */
const SKEW_TOLERANCE_MS = 60000;

const DAY_MS = 86400000;

/** Refusal codes. Every one of these means: ZERO deletions. */
const REFUSAL = {
  LISTING_UNAVAILABLE: 'LISTING_UNAVAILABLE',
  EMPTY_LISTING: 'EMPTY_LISTING',
  POINTER_MISSING: 'POINTER_MISSING'
};

function toMillis(value) {
  if (value === null || value === undefined) return null;
  if (value instanceof Date) {
    const t = value.getTime();
    return Number.isNaN(t) ? null : t;
  }
  const parsed = Date.parse(String(value));
  return Number.isNaN(parsed) ? null : parsed;
}

/**
 * Epoch ms encoded in an archive filename, or null if the name is not strictly the
 * shape performCosmosBackup() writes. Null is never treated as "assume it is old".
 */
function timestampFromArchiveName(name) {
  const m = ARCHIVE_TIMESTAMP_RE.exec(String(name || ''));
  if (!m) return null;
  const [, y, mo, d, h, mi, s, ms] = m;
  const t = Date.UTC(+y, +mo - 1, +d, +h, +mi, +s, +ms);
  return Number.isNaN(t) ? null : t;
}

/**
 * An empty, explicitly-refused plan. Used for every path where we are not certain we are
 * looking at a complete listing of the right container.
 *
 * CLAUDE.md mode 7: "A fallback path may never be more destructive than the primary
 * path. When the safe operation is unavailable, do nothing and report it."
 */
function refusedPlan(code, reason, nowMs) {
  return {
    ok: false,
    refusalCode: code,
    refusalReason: reason,
    toDelete: [],
    toKeep: [],
    sidecarsToDelete: [],
    ignored: [],
    protectedByFloor: [],
    archivesWithoutSidecar: [],
    skewWarnings: [],
    archiveCount: 0,
    cutoffIso: Number.isFinite(nowMs) ? new Date(nowMs - RETENTION_DAYS * DAY_MS).toISOString() : null,
    retentionDays: RETENTION_DAYS,
    minKeepNewest: MIN_KEEP_NEWEST,
    container: BACKUP_CONTAINER
  };
}

/**
 * Pure retention selector. `nowMs` is a parameter — the clock is NEVER read here.
 *
 * Pass the COMPLETE container listing. A caller that could not finish enumerating the
 * container must pass `null` (or nothing) rather than a partial array: a partial list
 * plus a delete loop deletes everything you could not see.
 *
 * @param {Array<{name: string, lastModified: (Date|string|null)}>|null} blobs
 * @param {number} nowMs epoch milliseconds
 * @returns {object} plan; `ok === false` always means toDelete/sidecarsToDelete are empty
 */
function selectBackupsForDeletion(blobs, nowMs) {
  if (!Number.isFinite(nowMs)) {
    return refusedPlan(
      REFUSAL.LISTING_UNAVAILABLE,
      'Refusing to plan: nowMs must be a finite epoch-milliseconds value.',
      NaN
    );
  }
  if (!Array.isArray(blobs)) {
    return refusedPlan(
      REFUSAL.LISTING_UNAVAILABLE,
      `Refusing to plan: the ${BACKUP_CONTAINER} listing is unavailable (no array supplied). ` +
      'A prune is never planned from a partial or missing listing.',
      nowMs
    );
  }
  if (blobs.length === 0) {
    return refusedPlan(
      REFUSAL.EMPTY_LISTING,
      `Refusing to plan: the ${BACKUP_CONTAINER} listing is empty. An empty container and an ` +
      'unreadable one look identical from here, so nothing is selected.',
      nowMs
    );
  }

  const names = new Set();
  for (const blob of blobs) {
    if (blob && blob.name) names.add(String(blob.name));
  }
  if (!names.has(LATEST_POINTER)) {
    return refusedPlan(
      REFUSAL.POINTER_MISSING,
      `Refusing to plan: ${LATEST_POINTER} is not in this listing. Either this is not the ` +
      `${BACKUP_CONTAINER} container, or the listing is incomplete. Nothing is selected.`,
      nowMs
    );
  }

  const candidates = [];
  const ignored = [];
  const skewWarnings = [];
  const sidecarNames = new Set();

  for (const blob of blobs) {
    if (!blob || !blob.name) {
      ignored.push(blob);
      continue;
    }
    const name = String(blob.name);
    if (name.endsWith('.sha256')) {
      sidecarNames.add(name);
      ignored.push(blob);
      continue;
    }
    if (name === LATEST_POINTER) {
      // A pointer, not an archive. Never deletable, at any age.
      ignored.push(blob);
      continue;
    }
    if (!ARCHIVE_RE.test(name)) {
      ignored.push(blob);
      continue;
    }

    const filenameMs = timestampFromArchiveName(name);
    const lastModifiedMs = toMillis(blob.lastModified);
    if (filenameMs === null || lastModifiedMs === null) {
      // Age unknown => keep. Never guess an age for something we are about to delete.
      ignored.push(blob);
      continue;
    }
    if (Math.abs(filenameMs - lastModifiedMs) > SKEW_TOLERANCE_MS) {
      skewWarnings.push({
        name,
        filenameIso: new Date(filenameMs).toISOString(),
        lastModifiedIso: new Date(lastModifiedMs).toISOString(),
        skewMs: lastModifiedMs - filenameMs
      });
    }

    candidates.push({
      name,
      filenameMs,
      lastModifiedMs,
      // The younger of the two readings: disagreement can only ever keep a backup longer.
      ms: Math.max(filenameMs, lastModifiedMs)
    });
  }

  // Newest first — the floor is defined by recency.
  candidates.sort((a, b) => (b.ms - a.ms) || a.name.localeCompare(b.name));

  const cutoffMs = nowMs - RETENTION_DAYS * DAY_MS;
  const protectedByFloor = candidates.slice(0, MIN_KEEP_NEWEST);
  const floorNames = new Set(protectedByFloor.map(c => c.name));

  const toDelete = [];
  const toKeep = [];
  for (const c of candidates) {
    const enriched = Object.assign({}, c, {
      ageDays: Math.round(((nowMs - c.ms) / DAY_MS) * 100) / 100
    });
    // Boundary: an archive exactly RETENTION_DAYS old is KEPT. Only strictly older
    // archives are deleted, because the requirement is "older than 15 days".
    const withinRetention = c.ms >= cutoffMs;
    if (withinRetention) {
      enriched.keepReason = `within ${RETENTION_DAYS}d window`;
      toKeep.push(enriched);
    } else if (floorNames.has(c.name)) {
      enriched.keepReason = `newest-${MIN_KEEP_NEWEST} floor`;
      toKeep.push(enriched);
    } else {
      toDelete.push(enriched);
    }
  }

  const sidecarsToDelete = toDelete
    .map(c => `${c.name}.sha256`)
    .filter(name => sidecarNames.has(name));

  const archivesWithoutSidecar = candidates
    .filter(c => !sidecarNames.has(`${c.name}.sha256`))
    .map(c => c.name);

  return {
    ok: true,
    refusalCode: null,
    refusalReason: null,
    toDelete,
    toKeep,
    sidecarsToDelete,
    ignored,
    protectedByFloor,
    archivesWithoutSidecar,
    skewWarnings,
    archiveCount: candidates.length,
    cutoffIso: new Date(cutoffMs).toISOString(),
    retentionDays: RETENTION_DAYS,
    minKeepNewest: MIN_KEEP_NEWEST,
    container: BACKUP_CONTAINER
  };
}

/**
 * The delete order for a plan: each archive immediately followed by its own sidecar.
 *
 * Archive FIRST, then its sidecar, deliberately. If the pair is interrupted between the
 * two deletes there are two possible wreckages, and they are not equally bad:
 *   - sidecar deleted, archive left  => an archive nobody can verify, which a future
 *     restore may trust blindly. Worst outcome.
 *   - archive deleted, sidecar left  => a 110-byte orphan pointing at nothing. Harmless
 *     and trivially detectable.
 * Deleting the archive first makes the second case the only reachable one.
 *
 * @returns {Array<{archive: string, sidecar: (string|null)}>}
 */
function buildDeletionPairs(plan) {
  if (!plan || plan.ok !== true) return [];
  const sidecars = new Set(plan.sidecarsToDelete || []);
  return (plan.toDelete || []).map(c => {
    const sidecarName = `${c.name}.sha256`;
    return { archive: c.name, sidecar: sidecars.has(sidecarName) ? sidecarName : null };
  });
}

/**
 * Executes a plan against an already-resolved blob container client. Shared by the CLI
 * and the timer so the delete ordering and the refusal rules exist ONCE.
 *
 * Refuses unless `apply === true` is passed explicitly — there is no truthy-ish opt-in.
 * Refuses outright for any plan with `ok !== true`, so a refused plan can never be
 * "executed anyway" by a caller that forgot to check the flag.
 *
 * If an archive delete fails, its sidecar is NOT deleted: a verifiable archive with its
 * sidecar intact is the state we want to leave behind on any error.
 *
 * @returns {Promise<{applied: boolean, deleted: string[], failures: string[], skipped: string[]}>}
 */
async function executeRetentionPlan(containerClient, plan, options) {
  const opts = options || {};
  const log = opts.log || console.log;
  const warn = opts.warn || console.warn;
  const apply = opts.apply === true;

  const result = { applied: false, deleted: [], failures: [], skipped: [] };

  if (!plan || plan.ok !== true) {
    const reason = plan && plan.refusalReason ? plan.refusalReason : 'no usable plan supplied';
    warn(`Retention execute refused: ${reason}`);
    return result;
  }
  if (!apply) {
    log('[DRY RUN] apply !== true — nothing was deleted.');
    return result;
  }
  if (!containerClient || typeof containerClient.getBlockBlobClient !== 'function') {
    warn('Retention execute refused: no usable container client was supplied.');
    return result;
  }

  result.applied = true;
  for (const pair of buildDeletionPairs(plan)) {
    let archiveDeleted = false;
    try {
      const res = await containerClient.getBlockBlobClient(pair.archive).deleteIfExists();
      if (res && res.succeeded) {
        archiveDeleted = true;
        result.deleted.push(pair.archive);
        log(`  deleted archive ${pair.archive}`);
      } else {
        result.failures.push(`${pair.archive}: blob not found`);
        warn(`  NOT deleted (missing): ${pair.archive}`);
      }
    } catch (err) {
      result.failures.push(`${pair.archive}: ${err.message}`);
      warn(`  delete FAILED: ${pair.archive} - ${err.message}`);
    }

    if (!pair.sidecar) continue;
    if (!archiveDeleted) {
      // Leave the archive verifiable. An unchecksummed archive is worse than an old one.
      result.skipped.push(pair.sidecar);
      warn(`  kept sidecar ${pair.sidecar} because its archive was not deleted`);
      continue;
    }
    try {
      const res = await containerClient.getBlockBlobClient(pair.sidecar).deleteIfExists();
      if (res && res.succeeded) {
        result.deleted.push(pair.sidecar);
        log(`  deleted sidecar ${pair.sidecar}`);
      } else {
        result.failures.push(`${pair.sidecar}: blob not found`);
        warn(`  orphan sidecar left behind (already missing): ${pair.sidecar}`);
      }
    } catch (err) {
      result.failures.push(`${pair.sidecar}: ${err.message}`);
      warn(`  ORPHAN SIDECAR: ${pair.sidecar} survived its deleted archive - ${err.message}`);
    }
  }
  return result;
}

module.exports = {
  RETENTION_DAYS,
  MIN_KEEP_NEWEST,
  BACKUP_CONTAINER,
  ARCHIVE_RE,
  ARCHIVE_TIMESTAMP_RE,
  LATEST_POINTER,
  SKEW_TOLERANCE_MS,
  REFUSAL,
  timestampFromArchiveName,
  selectBackupsForDeletion,
  buildDeletionPairs,
  executeRetentionPlan
};
